---
- hosts: git-remote
  vars:
      # server vars
      server_users:
         - name: "{{ git_user }}"
           shell: /bin/bash
           uid: 1501
           password: "{{ git_user_pass }}"
           group: git
      server_groups:
         - name: git
           gid: 1601
      # Service Packages definidos a 
      # nivel de host en inventories
      # Mariadb vars
      mysql_root_pass: '{{ mysql_root_pass }}' 
      mysql_bind_address: 'localhost'
      mysql_databases:
         - name: testing
           collation: "utf8_general_ci"
           encoding: "utf8"
      mysql_users:
         - name: '{{ mysql_user }}'
           pass: '{{ mysql_user_pass }}'
           priv: "*.*:ALL"
           host: "%"
  become: yes
  become_user: root
  become_method: sudo
  roles:
     - package_base


